version: "3"

services:
  v2ray:
    image: v2fly/v2fly-core:v4.45.2
    container_name: mcpv2
    restart: always
    ports:
      - "${runPort}:${runPort}"
    command: "v2ray -config=${api}/api/get_server_config?id=${nodeId}&token=${token}"
    volumes:
      - ./:/usr/local/share/v2ray


  v2scar:
    container_name: mcpv2scar
    image: debian:10
    restart: always
    depends_on:
      - v2ray
    links:
      - v2ray
    volumes:
      - ./:/root
    command: sh -c "apt update -y && apt install ca-certificates -y && chmod +x /root/v2scar_armlinux && /root/v2scar_armlinux -id=${nodeId} -gp=v2ray:8079"
